---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache2 web server
      apt:
        name: apache2
        state: present

    - name: Start Apache2 web server service
      service:
        name: apache2
        state: started

