---

- hosts: all
- become: yes
- tasks: Install webserver apache2 on ansible nodes
   apt:
    name:apache2
    state:present
- tasks: start the webserver apache2 on ansible nodes
   service:
    name: apache2
    state: started

