---
- hosts: all
  become: yes
  tasks:
    - name: Install and start Apache2 on Debian-based systems
      apt:
        name: apache2
        state: present
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: Install and start Apache2 on RedHat-based systems
      yum:
        name: httpd
        state: present
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"