---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu server
    apt:
      name: apache2
      state: present
    when:ansible_os_family =="Debian"

  - name: i want start the webserver on ubuntu server
    service:
     name: apache2
     state: started
    when:ansible_os_family =="Debian"

  - name: i want to install webserver on ubuntu server
    yum:
     name: httpd
     state: present
    when:ansible_os_family =="RedHat" 
  - name: i want start the webserver on ubuntu server
    service:
     name: httpd
     state: started   
    when:ansible_os_family =="RedHat"